name = "jsp690_complete"
version = "0.2.0"
defaultTargets = ["JSP690", "Transversal", "Complete690"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "5ed2965256430c3649e86755f9576b54eca72435"

[[lean_lib]]
name = "JSP690"

[[lean_lib]]
name = "Transversal"

[[lean_lib]]
name = "Complete690"
